const db = require('../db')
const Detail = require('../models/detail')
// const Culture = require('../models/culture')
// const Person = require('../models/person')
// const Places = require('../models/places')
// const Entertainment = require('../models/entertainment')

db.on('error', console.error.bind(console, 'MongoDB connection error'))

const main = async () => {
    // const culture1 = await new Culture ({tribe: 'Yoruba', language: 'Yoruba', religion: 'Islam, Pentecostalism, Traditional Worship', art: {artist: 'unknown', medium: 'woodcarving, sculpture, metal work, textiles, and beadwork', image: 'https://collectionapi.metmuseum.org/api/collection/v1/iiif/320382/677707/restricted'}})
    // culture1.save()

    // const culture2 = await new Culture ( {tribe: 'Igbo', language: 'Igbo', religion: 'Catholicism, Traditional Worship',
    // art: {artist: 'unknown', medium: 'traditional figures, masks, artifacts and textiles, works in metals', image: 'https://i.pinimg.com/736x/54/e2/20/54e220a39858dab2b438f8a0e56ab672.jpg'}})
    // culture2.save()

    // const culture3 = await new Culture ({tribe: 'Hausa', language: 'Hausa', religion: 'Islam',
    // art: {artist: 'unknown', medium: 'calligraphy, basketry, leatherwork and metalwork', image: 'https://ids.si.edu/ids/deliveryService?id=NMAfA-R20001100&max=327'}})
    // culture3.save()

      
    // const person1 = await new Person ({name: 'Aisha Yesufu', deed: 'Nigerian activist and businesswoman', blurb: 'She co-founded the #BringBackOurGirls movement, which brings attention to the abduction of over 200 girls from a secondary school in Chibok, Nigeria on 14 April 2014, by the terrorist group Boko Haram.She has also been prominently involved in the End SARS movement against police brutality in Nigeria.', image: 'https://www.thecityceleb.com/wp-content/uploads/2020/10/Aisha-Yusuf-Biography-TheCityCeleb.Com_.jpeg', source: 'https://en.wikipedia.org/wiki/Aisha_Yesufu'})
    // person1.save()

    // const person2 = await new Person ({name: 'Fela Anikulakpo Kuti', deed: 'Musician, Pioneer of Afrobeat Music; opposed the then oppressive military regime', blurb: 'Fela Kuti, byname of Olufela Olusegun Oludotun Ransome-Kuti, also called Fela Anikulapo-Kuti, (born October 15, 1938, Abeokuta, Nigeria—died August 2, 1997, Lagos), Nigerian musician and activist who launched a modern style of music called Afro-beat, which fused American blues, jazz, and funk with traditional Yoruba music.', image: 'https://www.rollingstone.com/wp-content/uploads/2021/10/FelaKuti.jpg?resize=1800,1200&w=450', source: 'https://www.britannica.com/biography/Fela-Kuti'})
    // person2.save()

    // const person3 = await new Person ({name: 'Chinua Achebe', deed: 'Author, Things Fall Apart', blurb: 'Chinua Achebe, in full Albert Chinualumogu Achebe, (born November 16, 1930, Ogidi, Nigeria—died March 21, 2013, Boston, Massachusetts, U.S.), Nigerian novelist acclaimed for his unsentimental depictions of the social and psychological disorientation accompanying the imposition of Western customs and values upon traditional African society. ', image: 'https://static01.nyt.com/images/2013/03/23/books/23achebe_337/23achebe_337-superJumbo.jpg', source: 'https://www.britannica.com/biography/Chinua-Achebe'})
    // person3.save()


    // const places1 = await new Places ({name: 'Awhum Caves and Waterfalls', location: 'Udi Local Government Area, Enugu State', description: 'The Awhum Waterfall is formed out of a massive outcrop of granite rock with water flow at the top forming a stream. Some part of the waterfall is usually warm through the seasons. The Awhum waterfall is 30 metres high and is located around the Awhum Monastery.', image: 'https://i.pinimg.com/736x/88/f7/74/88f7743bd4d4c83f9b177d10c11df835--pond-waterfall-water-features.jpg', source: 'https://en.wikipedia.org/wiki/Awhum_Waterfall'})
    // places1.save() 

    // const places2 = await new Places ({name: 'Osun-Osogbo Sacred Grove', location: 'Osogbo, Osun State', description: 'The Osun-Osogbo Grove is several centuries old and is among the last of the sacred forests that once adjoined the edges of most Yoruba cities before extensive urbanization. In recognition of its global significance and its cultural value, the Sacred Grove was inscribed as a UNESCO World Heritage Site in 2005.', image: 'https://guardian.ng/wp-content/uploads/2017/06/Osogbo.jpg', source: 'https://en.wikipedia.org/wiki/Osun-Osogbo'})
    // places2.save() 

    // const places3 = await new Places ({name: 'Yankari Game Reserve', location: 'Bauchi State', description: `Yankari National Park is a large wildlife park located in the south-central part of Bauchi State, in northeastern Nigeria. It covers an area of about 2,244 square kilometres (866 sq mi) and is home to several natural warm water springs, as well as a wide variety of flora and fauna. Its location in the heartland of the West African savanna makes it a unique way for tourists and holidaymakers to watch wildlife in its natural habitat. Yankari was created as a game reserve in 1956, but later designated Nigeria's biggest national park in 1991. It is the most popular destination for tourists in Nigeria and, as such, plays a crucial role in the development and promotion of tourism and ecotourism in Nigeria.`, image: 'https://kiddiesafricanews.com/wp-content/uploads/2020/09/Yankari-Game-Reserve.jpg', source: 'https://en.wikipedia.org/wiki/Yankari_National_Park'})
    // places3.save() 


    // const entertainment1 = await new Entertainment ({music: {artiste: 'Wizkid', song: 'Anoti', genre: 'Afrobeats'}, books: {bookTitle: 'Half of a Yellow Sun', bookAuthor: 'Chimamanda Ngozi Adichie', bookImage: 'https://farafinabooks.files.wordpress.com/2013/04/half-of-a-yellow-sun.jpg'}, film: {filmTitle: 'A Naija Christmas', leadAct: 'Rachel Oniga'}})
    // entertainment1.save()

    // const entertainment2 = await new Entertainment ({music: {artiste: 'Davido', song: 'If', genre: 'Afrobeats'}, books: {bookTitle: 'Ake', bookAuthor: 'Wole Soyinka', bookImage: 'https://bookcraftafrica.com/public/images/newbookcovers/4377_Ake_front_cover.jpg'}, film: {filmTitle: 'Isoken', leadAct: 'Dakore Egbuson'}})
    // entertainment2.save()

    // const entertainment3 = await new Entertainment ({music: {artiste: 'Asa', song: 'IDG', genre: 'Afrobeats'}, books: {bookTitle: 'Everything good will come', bookAuthor: 'Sefi Atta', bookImage: 'https://farafinabooks.files.wordpress.com/2010/10/everythin-good-cover2.jpg'}, film: {filmTitle: `Who's the Boss`, leadAct: 'Sharon Ooja'}})
    // entertainment3.save()

    // const details = [
    //     {culture: {tribe: 'Yoruba', language: 'Yoruba', religion: 'Islam, Pentecostalism, Traditional Worship', art: {artist: 'unknown', medium: 'woodcarving, sculpture, metal work, textiles, and beadwork', image: 'https://collectionapi.metmuseum.org/api/collection/v1/iiif/320382/677707/restricted'}}, people: {name: 'Aisha Yesufu', deed: 'Nigerian activist and businesswoman', blurb: 'She co-founded the #BringBackOurGirls movement, which brings attention to the abduction of over 200 girls from a secondary school in Chibok, Nigeria on 14 April 2014, by the terrorist group Boko Haram.She has also been prominently involved in the End SARS movement against police brutality in Nigeria.', image: 'https://www.thecityceleb.com/wp-content/uploads/2020/10/Aisha-Yusuf-Biography-TheCityCeleb.Com_.jpeg', source: 'https://en.wikipedia.org/wiki/Aisha_Yesufu'}, places: {name: 'Awhum Caves and Waterfalls', location: 'Udi Local Government Area, Enugu State', description: 'The Awhum Waterfall is formed out of a massive outcrop of granite rock with water flow at the top forming a stream. Some part of the waterfall is usually warm through the seasons. The Awhum waterfall is 30 metres high and is located around the Awhum Monastery.', image: 'https://i.pinimg.com/736x/88/f7/74/88f7743bd4d4c83f9b177d10c11df835--pond-waterfall-water-features.jpg', source: 'https://en.wikipedia.org/wiki/Awhum_Waterfall'}, entertainment: {music: {artiste: 'Wizkid', song: 'Anoti', genre: 'Afrobeats'}, books: {bookTitle: 'Half of a Yellow Sun', bookAuthor: 'Chimamanda Ngozi Adichie', bookImage: 'https://farafinabooks.files.wordpress.com/2013/04/half-of-a-yellow-sun.jpg'}, film: {filmTitle: 'A Naija Christmas', leadAct: 'Rachel Oniga'}}},
        

    //     {culture: {tribe: 'Igbo', language: 'Igbo', religion: 'Catholicism, Traditional Worship',
    //     art: {artist: 'unknown', medium: 'traditional figures, masks, artifacts and textiles, works in metals', image: 'https://i.pinimg.com/736x/54/e2/20/54e220a39858dab2b438f8a0e56ab672.jpg'}}, people: {name: 'Fela Anikulakpo Kuti', deed: 'Musician, Pioneer of Afrobeat Music; opposed the then oppressive military regime', blurb: 'Fela Kuti, byname of Olufela Olusegun Oludotun Ransome-Kuti, also called Fela Anikulapo-Kuti, (born October 15, 1938, Abeokuta, Nigeria—died August 2, 1997, Lagos), Nigerian musician and activist who launched a modern style of music called Afro-beat, which fused American blues, jazz, and funk with traditional Yoruba music.', image: 'https://www.rollingstone.com/wp-content/uploads/2021/10/FelaKuti.jpg?resize=1800,1200&w=450', source: 'https://www.britannica.com/biography/Fela-Kuti'}, places: {name: 'Osun-Osogbo Sacred Grove', location: 'Osogbo, Osun State', description: 'The Osun-Osogbo Grove is several centuries old and is among the last of the sacred forests that once adjoined the edges of most Yoruba cities before extensive urbanization. In recognition of its global significance and its cultural value, the Sacred Grove was inscribed as a UNESCO World Heritage Site in 2005.', image: 'https://guardian.ng/wp-content/uploads/2017/06/Osogbo.jpg', source: 'https://en.wikipedia.org/wiki/Osun-Osogbo'}, entertainment: {music: {artiste: 'Davido', song: 'If', genre: 'Afrobeats'}, books: {bookTitle: 'Ake', bookAuthor: 'Wole Soyinka', bookImage: 'https://bookcraftafrica.com/public/images/newbookcovers/4377_Ake_front_cover.jpg'}, film: {filmTitle: 'Isoken', leadAct: 'Dakore Egbuson'}}},


    //     {culture: {tribe: 'Hausa', language: 'Hausa', religion: 'Islam',
    //     art: {artist: 'unknown', medium: 'calligraphy, basketry, leatherwork and metalwork', image: 'https://ids.si.edu/ids/deliveryService?id=NMAfA-R20001100&max=327'}}, people: {name: 'Chinua Achebe', deed: 'Author, Things Fall Apart', blurb: 'Chinua Achebe, in full Albert Chinualumogu Achebe, (born November 16, 1930, Ogidi, Nigeria—died March 21, 2013, Boston, Massachusetts, U.S.), Nigerian novelist acclaimed for his unsentimental depictions of the social and psychological disorientation accompanying the imposition of Western customs and values upon traditional African society. ', image: 'https://static01.nyt.com/images/2013/03/23/books/23achebe_337/23achebe_337-superJumbo.jpg', source: 'https://www.britannica.com/biography/Chinua-Achebe'}, places: {name: 'Yankari Game Reserve', location: 'Bauchi State', description: `Yankari National Park is a large wildlife park located in the south-central part of Bauchi State, in northeastern Nigeria. It covers an area of about 2,244 square kilometres (866 sq mi) and is home to several natural warm water springs, as well as a wide variety of flora and fauna. Its location in the heartland of the West African savanna makes it a unique way for tourists and holidaymakers to watch wildlife in its natural habitat. Yankari was created as a game reserve in 1956, but later designated Nigeria's biggest national park in 1991. It is the most popular destination for tourists in Nigeria and, as such, plays a crucial role in the development and promotion of tourism and ecotourism in Nigeria.`, image: 'https://kiddiesafricanews.com/wp-content/uploads/2020/09/Yankari-Game-Reserve.jpg', source: 'https://en.wikipedia.org/wiki/Yankari_National_Park'}, entertainment: {music: {artiste: 'Asa', song: 'IDG', genre: 'Afrobeats'}, books: {bookTitle: 'Everything good will come', bookAuthor: 'Sefi Atta', bookImage: 'https://farafinabooks.files.wordpress.com/2010/10/everythin-good-cover2.jpg'}, film: {filmTitle: `Who's the Boss`, leadAct: 'Sharon Ooja'}}}
    // ]
    const details = [
         {book: "Half of a Yellow Sun", blurb: "Half of a Yellow Sun recreates a seminal moment in Nigerian history: Biafra’s impassioned struggle to establish an independent republic in Nigeria and the chilling violence that followed.", bookImage: "https://farafinabooks.files.wordpress.com/2013/04/half-of-a-yellow-sun.jpg", author: "Chimamanda Ngozi Adichie", bio: "Chimamanda Ngozi Adichie, (born September 15, 1977, Enugu, Nigeria), Nigerian author whose work drew extensively on the Biafran war in Nigeria during the late 1960s.", authorImage: "https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/GVJ7KSU5JUI6XN5IAFFRJLVZ4Q.jpg"},

        {book: "Ake", blurb: `A dazzling memoir of a Nigerian childhood from Nobel Prize-winning Nigerian novelist, playwright, and poet Wole Soyinka. Aké: The Years of Childhood gives us the story of Soyinka's boyhood before and during World War II in a Yoruba village in western Nigeria called Aké.`, bookImage: "https://bookcraftafrica.com/public/images/newbookcovers/4377_Ake_front_cover.jpg", author: "Wole Soyinka", bio: "Wole Soyinka, in full Akinwande Oluwole Soyinka, (born July 13, 1934, Abeokuta, Nigeria), Nigerian playwright and political activist who received the Nobel Prize for Literature in 1986. He sometimes wrote of modern West Africa in a satirical style, but his serious intent and his belief in the evils inherent in the exercise of power were usually evident in his work as well.", authorImage: "https://ca-times.brightspotcdn.com/dims4/default/343663f/2147483647/strip/true/crop/1334x1945+0+0/resize/1019x1486!/quality/90/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F2d%2F6a%2F0c6608cd479094fe6a1e8a2e0619%2Fla-ca-wole-soyinka.jpg"}, 

        {book: "Everything good will come", blurb: "Everything Good Will Come is a coming-of-age novel by Nigerian author Sefi Atta about a girl growing into a woman in postcolonial Nigeria and England. It was published by Interlink World Fiction in 2005, and won the Wole Soyinka Prize for Literature in Africa.", bookImage: "https://farafinabooks.files.wordpress.com/2010/10/everythin-good-cover2.jpg", author: "Sefi Atta", bio: "Sefi Atta is a prize-winning Nigerian-American novelist, short-story writer, playwright and screenwriter. Her books have been translated into many languages, radio plays have been broadcast by the BBC, and her stage plays have been performed internationally.", authorImage: "https://miro.medium.com/max/1400/1*a-IjrD2QOXEYKARACOJ5EA.jpeg"},

        {book: "Things Fall Apart", blurb: "The novel chronicles the life of Okonkwo, the leader of an Igbo community, from the events leading up to his banishment from the community for accidentally killing a clansman, through the seven years of his exile, to his return, and it addresses a particular problem of emergent Africa—the intrusion in the 1890s of white missionaries and colonial government into tribal Igbo society.", bookImage: "https://static01.nyt.com/images/2013/03/23/books/23achebe_337/23achebe_337-superJumbo.jpg", author: "Chinua Achebe", bio: "Chinua Achebe, in full Albert Chinualumogu Achebe, (born November 16, 1930, Ogidi, Nigeria—died March 21, 2013, Boston, Massachusetts, U.S.), Nigerian novelist acclaimed for his unsentimental depictions of the social and psychological disorientation accompanying the imposition of Western customs and values upon traditional African society.", authorImage: "https://static01.nyt.com/images/2013/03/23/books/23achebe_337/23achebe_337-superJumbo.jpg"},

        {book: "The Secret Lives Of Baba Segi’s Wives", blurb: "Published in 2012, this novel is a perceptive, entertaining, and eye-opening novel of polygamy in modern-day Nigeria. The struggles, rivalries, intricate family politics, and the interplay of personalities and relationships within the complex private world of a polygamous union come to life in this exciting work of fiction.", bookImage: "https://serpentstail.com/wp-content/uploads/sites/2/2020/12/getimage-3.jpeg",author: "Lola Shoneyin", bio: "Lola Shoneyin is a Nigerian poet and author who launched her debut novel, The Secret Lives of Baba Segi's Wives, in the UK in May 2010. Shoneyin has forged a reputation as an adventurous, humorous and outspoken poet, having published three volumes of poetry.", authorImage: "https://aalbc.com/author-photos/Lola-Shoneyin.jpg"},
            
        {book: "The Joys Of Motherhood", blurb: "In this feminist classic, Nnu Ego is a Nigerian woman struggling in a patriarchal society. Unable to conceive in her first marriage, Nnu is banished to Lagos where she succeeds in becoming a mother. Nnu Ego must fiercely protect herself and her children when she is abandoned by her husband and her people.", bookImage: "https://images-na.ssl-images-amazon.com/images/I/51DvLRFmDGL.jpg",
        author: "Buchi Emecheta", bio: `Florence Onyebuchi "Buchi" Emecheta OBE was a Nigerian-born novelist, based in the UK from 1962, who also wrote plays and an autobiography, as well as works for children. She was the author of more than 20 books, including Second Class Citizen, The Bride Price, The Slave Girl and The Joys of Motherhood.`, authorImage: "https://images.wakelet.com/resize?id=7b4a3dc3-053a-4170-ba6e-7966d6e0ba48&h=300&w=400&q=85"},    
        
        {book: "Akata Witch", blurb: `Affectionately dubbed "the Nigerian Harry Potter," Akata Witch weaves together a heart-pounding tale of magic, mystery, and finding one's place in the world. Twelve-year-old Sunny lives in Nigeria, but she was born American. Her features are African, but she's albino. She's a terrific athlete, but can't go out into the sun to play soccer. There seems to be no place where she fits in. And then she discovers something amazing—she is a "free agent" with latent magical power. Soon she's part of a quartet of magic students, studying the visible and invisible, learning to change reality. But will it be enough to help them when they are asked to catch a career criminal who knows magic too?`, bookImage: "https://images1.penguinrandomhouse.com/cover/9781101513798", author: "Nnedi Okoroafor", bio: `Nnedimma Nkemdili "Nnedi" Okorafor is a Nigerian-American writer of fantasy and science fiction for both children and adults. She is best known for her Binti Series and her novels Who Fears Death, Zahrah the Windseeker, Akata Witch, Akata Warrior, Lagoon and Remote Control. She has also written for comics and film.`, authorImage: "https://images.gr-assets.com/authors/1507148868p8/588356.jpg"},

        {book: "Children of Blood and Bone", blurb: "With five starred reviews, Tomi Adeyemi’s West African-inspired fantasy debut, and instant #1 New York Times Bestseller, conjures a world of magic and danger, perfect for fans of Leigh Bardugo and Sabaa Tahir.", bookImage: "https://images-na.ssl-images-amazon.com/images/I/A1agLFsWkOL.jpg", author: "Tomi Adeyemi",bio: `Tomi Adeyemi (born August 1, 1993) is a Nigerian-American novelist and creative writing coach. She is known for her novel Children of Blood and Bone, the first in the Legacy of Orïsha trilogy published by Henry Holt Books for Young Readers, which won the 2018 Andre Norton Award for Young Adult Science Fiction and Fantasy, the 2019 Waterstones Book Prize, and the 2019 Hugo Lodestar Award for Best Young Adult Book.In 2019, she was named to the Forbes 30 Under 30 list. In 2020, she was named to the TIME 100 Most Influential People of 2020 in the "Pioneers" category.`, authorImage: "https://images.gr-assets.com/authors/1573251060p8/16642745.jpg"},

        {book: "Say You're One of Them", blurb: "Say You're One of Them is a collection of short stories by Nigerian writer Uwem Akpan, first published in 2008. Containing five stories, each set in a different African country, this collection won the 2009 Commonwealth Writers Prize and the 2009 Beyond Margins Award.", bookImage: "https://www.hachettebookgroup.com/wp-content/uploads/2017/06/9780316086370.jpg?fit=1718%2C2600", author: "Uwem Akpan", bio: `Uwem Akpan is a Nigerian writer. He is the author of Say You're One of Them, a collection of five stories published by Little, Brown & Company. The book inspired Angelique Kidjo to write the song "Agbalagba". It made the Best of the Year list at People magazine, The Wall Street Journal, and other places.`, authorImage: `https://ccfw.calvin.edu/media/11660/screenshot-27.png`},

        {book: "I Do Not Come To You By Chance", blurb: "A deeply moving debut novel set amid the perilous world of Nigerian email scams, I Do Not Come to You by Chance tells the story of one young man and the family who loves him.", bookImage: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1408307899l/7663356.jpg", author: "Adaobi Tricia Nwaubani", bio: "Adaobi Tricia Obinne Nwaubani is a Nigerian novelist, humorist, essayist and journalist. Her debut novel, I Do Not Come To You By Chance, won the 2010 Commonwealth Writers' Prize for Best First Book, a Betty Trask First Book award, and was named by The Washington Post as one of the Best Books of 2009.", authorImage: "https://masobebooks.com/wp-content/uploads/2016/04/Adaobi-Tricia-1.jpg"},  

        {book: "Love Is Power, Or Something Like That: Stories", blurb: "In these nine blistering stories cavort jealous husbands, kissing cousins, teenage internet hustlers, democratic bus rides, home exorcisms and bowls of dubious catfish peppersoup: this is a searing, savage portrait of an utterly modern Nigeria. Dark yet disarming, in prose that is tough, vigorous and immediately distinctive, Love is Power, Or Something Like That is a phenomenal short story collection from a palpably talented new writer.", bookImage: "http://3.bp.blogspot.com/-5anjoAcsysQ/Uqm_QUcB3jI/AAAAAAAAAr4/GsZoP7LKi9k/s1600/Love+Is+Power,+or+Something+Like+That.jpg", author: "A. Igoni Barrett", bio: "Adrian Igonibo Barrett is a Nigerian writer of short stories and novels. In 2014, he was named on the Africa39 list of writers aged under 40 with potential and talent to define future trends in African literature.", authorImage: "https://www.hurstonwright.org/wp-content/uploads/2017/09/ignoli-Barrett.png"},

        {book: "Beasts of No Nation", blurb: "Beasts of No Nation is a 2005 novel by the Nigerian-American author Uzodinma Iweala, that takes its title from Fela Kuti's 1989 album with the same name. The book won the 2005 Art Seidenbaum Award for First Fiction and was adapted as a movie in 2015.", bookImage: "https://m.media-amazon.com/images/I/51b1jLOqIlL.jpg",author: "Uzodinma Iweala", bio: "Uzodinma Iweala is a Nigerian-American author and medical doctor. His debut novel, Beasts of No Nation, is a formation of his thesis work at Harvard. It depicts a child soldier in an unnamed African country.", authorImage: "https://i.harperapps.com/authors/29377/x500.JPG"}
    ]
    await Detail.insertMany(details)
    console.log('Details database created!')
}

const run = async () => {
    await main()
    db.close()
}

run()